/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Surface_mesher;
import CGAL.Kernel.Point_3;
public class Surface_mesh_default_triangulation_3_Vertex_handle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Surface_mesh_default_triangulation_3_Vertex_handle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Surface_mesh_default_triangulation_3_Vertex_handle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Surface_mesherJNI.delete_Surface_mesh_default_triangulation_3_Vertex_handle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Surface_mesh_default_triangulation_3_Vertex_handle() {
    this(CGAL_Surface_mesherJNI.new_Surface_mesh_default_triangulation_3_Vertex_handle(), true);
  }

  public Point_3 point() {
    return new Point_3(CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_point__SWIG_0(swigCPtr, this), true);
  }

  public void point(Point_3 ref) {
    CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_point__SWIG_1(swigCPtr, this, Point_3.getCPtr(ref), ref);
  }

  public Surface_mesh_default_triangulation_3_Cell_handle cell() {
    return new Surface_mesh_default_triangulation_3_Cell_handle(CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_cell__SWIG_0(swigCPtr, this), true);
  }

  public void cell(Surface_mesh_default_triangulation_3_Cell_handle ref) {
    CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_cell__SWIG_1(swigCPtr, this, Surface_mesh_default_triangulation_3_Cell_handle.getCPtr(ref), ref);
  }

  public void set_cell(Surface_mesh_default_triangulation_3_Cell_handle c) {
    CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_set_cell(swigCPtr, this, Surface_mesh_default_triangulation_3_Cell_handle.getCPtr(c), c);
  }

  public void set_point(Point_3 c) {
    CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_set_point(swigCPtr, this, Point_3.getCPtr(c), c);
  }

  public boolean is_valid() {
    return CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_is_valid__SWIG_0(swigCPtr, this);
  }

  public boolean is_valid(boolean c) {
    return CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_is_valid__SWIG_1(swigCPtr, this, c);
  }

  public boolean equals(Surface_mesh_default_triangulation_3_Vertex_handle v) {
    return CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_equals(swigCPtr, this, Surface_mesh_default_triangulation_3_Vertex_handle.getCPtr(v), v);
  }

  public Surface_mesh_default_triangulation_3_Vertex_handle clone() {
    return new Surface_mesh_default_triangulation_3_Vertex_handle(CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Surface_mesh_default_triangulation_3_Vertex_handle other) {
    CGAL_Surface_mesherJNI.Surface_mesh_default_triangulation_3_Vertex_handle_clone__SWIG_1(swigCPtr, this, Surface_mesh_default_triangulation_3_Vertex_handle.getCPtr(other), other);
  }

}
