/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polyhedron_3;
import CGAL.Java.JavaData; 
public class Polyhedron_3_Facet_handle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Polyhedron_3_Facet_handle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Polyhedron_3_Facet_handle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polyhedron_3JNI.delete_Polyhedron_3_Facet_handle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Polyhedron_3_Facet_handle() {
    this(CGAL_Polyhedron_3JNI.new_Polyhedron_3_Facet_handle(), true);
  }

  public Polyhedron_3_Halfedge_handle halfedge() {
    return new Polyhedron_3_Halfedge_handle(CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_halfedge__SWIG_0(swigCPtr, this), true);
  }

  public void halfedge(Polyhedron_3_Halfedge_handle ref) {
    CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_halfedge__SWIG_1(swigCPtr, this, Polyhedron_3_Halfedge_handle.getCPtr(ref), ref);
  }

  public Polyhedron_3_Halfedge_around_facet_circulator facet_begin() {
    return new Polyhedron_3_Halfedge_around_facet_circulator(CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_facet_begin(swigCPtr, this), true);
  }

  public void set_halfedge(Polyhedron_3_Halfedge_handle c) {
    CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_set_halfedge(swigCPtr, this, Polyhedron_3_Halfedge_handle.getCPtr(c), c);
  }

  public long facet_degree() {
    return CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_facet_degree(swigCPtr, this);
  }

  public boolean is_triangle() {
    return CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_is_triangle(swigCPtr, this);
  }

  public boolean is_quad() {
    return CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_is_quad(swigCPtr, this);
  }

  public boolean equals(Polyhedron_3_Facet_handle f) {
    return CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_equals(swigCPtr, this, Polyhedron_3_Facet_handle.getCPtr(f), f);
  }

  public int hashCode() {
    return CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_hashCode(swigCPtr, this);
  }

  public int id() {
    return CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_id(swigCPtr, this);
  }

  public void set_id(int i) {
    CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_set_id(swigCPtr, this, i);
  }

  public Polyhedron_3_Facet_handle clone() {
    return new Polyhedron_3_Facet_handle(CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Polyhedron_3_Facet_handle other) {
    CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_clone__SWIG_1(swigCPtr, this, Polyhedron_3_Facet_handle.getCPtr(other), other);
  }

  public JavaData info() {
    return new JavaData(CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_info(swigCPtr, this), false);
  }

  public void get_info(JavaData jd) {
    CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_get_info(swigCPtr, this, JavaData.getCPtr(jd), jd);
  }

  public void set_info(JavaData jd) {
    CGAL_Polyhedron_3JNI.Polyhedron_3_Facet_handle_set_info(swigCPtr, this, JavaData.getCPtr(jd), jd);
  }

}
