/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Polyhedron_3;
import CGAL.Kernel.Point_3; import java.util.Iterator;
public class Polyhedron_3_Modifier_triangular_facets {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Polyhedron_3_Modifier_triangular_facets(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Polyhedron_3_Modifier_triangular_facets obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Polyhedron_3JNI.delete_Polyhedron_3_Modifier_triangular_facets(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Polyhedron_3_Modifier_base get_modifier() {
    return new Polyhedron_3_Modifier_base(CGAL_Polyhedron_3JNI.Polyhedron_3_Modifier_triangular_facets_get_modifier(swigCPtr, this), true);
  }

  public void set_modifier_data(Iterator<Point_3> pt_range, Iterator<Integer_triple> int_range) {
    CGAL_Polyhedron_3JNI.Polyhedron_3_Modifier_triangular_facets_set_modifier_data(swigCPtr, this, pt_range, int_range);
  }

  public Polyhedron_3_Modifier_triangular_facets() {
    this(CGAL_Polyhedron_3JNI.new_Polyhedron_3_Modifier_triangular_facets(), true);
  }

}
