/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Mesh_2;
import CGAL.Kernel.Point_2;
public class Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Mesh_2JNI.delete_Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle() {
    this(CGAL_Mesh_2JNI.new_Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle(), true);
  }

  public Point_2 point() {
    return new Point_2(CGAL_Mesh_2JNI.Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle_point__SWIG_0(swigCPtr, this), true);
  }

  public void point(Point_2 ref) {
    CGAL_Mesh_2JNI.Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle_point__SWIG_1(swigCPtr, this, Point_2.getCPtr(ref), ref);
  }

  public void set_point(Point_2 c) {
    CGAL_Mesh_2JNI.Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle_set_point(swigCPtr, this, Point_2.getCPtr(c), c);
  }

  public boolean equals(Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle v) {
    return CGAL_Mesh_2JNI.Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle_equals(swigCPtr, this, Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle.getCPtr(v), v);
  }

  public Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle clone() {
    return new Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle(CGAL_Mesh_2JNI.Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle other) {
    CGAL_Mesh_2JNI.Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle_clone__SWIG_1(swigCPtr, this, Mesh_2_Constrained_Delaunay_triangulation_2_Vertex_handle.getCPtr(other), other);
  }

}
