/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Alpha_shape_2;

  import java.lang.Iterable;
  import java.lang.UnsupportedOperationException;
  import java.util.Iterator;
  
public class Alpha_shape_2_Alpha_iterator implements   Iterable<Double>, Iterator<Double>  {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Alpha_shape_2_Alpha_iterator(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Alpha_shape_2_Alpha_iterator obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_Alpha_shape_2JNI.delete_Alpha_shape_2_Alpha_iterator(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

    public void remove() {
      throw new UnsupportedOperationException();
    }
    
    public Iterator<Double> iterator() {
      return this;
    }

    public Double next() {
      return slow_next();
    }
  
  public Alpha_shape_2_Alpha_iterator() {
    this(CGAL_Alpha_shape_2JNI.new_Alpha_shape_2_Alpha_iterator(), true);
  }

  public Double slow_next() {
    return CGAL_Alpha_shape_2JNI.Alpha_shape_2_Alpha_iterator_slow_next(swigCPtr, this);
  }

  public boolean hasNext() {
    return CGAL_Alpha_shape_2JNI.Alpha_shape_2_Alpha_iterator_hasNext(swigCPtr, this);
  }

}
