/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Voronoi;
import CGAL.Kernel.Point_3;
import CGAL.Triangulation_3.Delaunay_triangulation_3;
import CGAL.Triangulation_3.Delaunay_triangulation_3_Cell_handle;
public class CGAL_Voronoi {
  public static void get_Voronoi(Delaunay_triangulation_3 dt, Delaunay_triangulation_3_Cell_handle cell, Point_3 voronoi_point) {
    CGAL_VoronoiJNI.get_Voronoi(Delaunay_triangulation_3.getCPtr(dt), dt, Delaunay_triangulation_3_Cell_handle.getCPtr(cell), cell, Point_3.getCPtr(voronoi_point), voronoi_point);
  }

}
