/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Point_3 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Point_3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Point_3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point_3() {
    this(CGAL_KernelJNI.new_Point_3__SWIG_0(), true);
  }

  public Point_3(double x, double y, double z) {
    this(CGAL_KernelJNI.new_Point_3__SWIG_1(x, y, z), true);
  }

  public double x() {
    return CGAL_KernelJNI.Point_3_x(swigCPtr, this);
  }

  public double y() {
    return CGAL_KernelJNI.Point_3_y(swigCPtr, this);
  }

  public double z() {
    return CGAL_KernelJNI.Point_3_z(swigCPtr, this);
  }

  public void set_coordinates(double x, double y, double z) {
    CGAL_KernelJNI.Point_3_set_coordinates(swigCPtr, this, x, y, z);
  }

  public boolean equals(Point_3 p) {
    return CGAL_KernelJNI.Point_3_equals(swigCPtr, this, Point_3.getCPtr(p), p);
  }

  public String toString() {
    return CGAL_KernelJNI.Point_3_toString(swigCPtr, this);
  }

  public Point_3 clone() {
    return new Point_3(CGAL_KernelJNI.Point_3_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Point_3 other) {
    CGAL_KernelJNI.Point_3_clone__SWIG_1(swigCPtr, this, Point_3.getCPtr(other), other);
  }

}
