/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Point_2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Point_2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Point_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Point_2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Point_2() {
    this(CGAL_KernelJNI.new_Point_2__SWIG_0(), true);
  }

  public Point_2(double x, double y) {
    this(CGAL_KernelJNI.new_Point_2__SWIG_1(x, y), true);
  }

  public double x() {
    return CGAL_KernelJNI.Point_2_x(swigCPtr, this);
  }

  public double y() {
    return CGAL_KernelJNI.Point_2_y(swigCPtr, this);
  }

  public void set_coordinates(double x, double y) {
    CGAL_KernelJNI.Point_2_set_coordinates(swigCPtr, this, x, y);
  }

  public boolean equals(Point_2 p) {
    return CGAL_KernelJNI.Point_2_equals(swigCPtr, this, Point_2.getCPtr(p), p);
  }

  public String toString() {
    return CGAL_KernelJNI.Point_2_toString(swigCPtr, this);
  }

  public Point_2 clone() {
    return new Point_2(CGAL_KernelJNI.Point_2_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Point_2 other) {
    CGAL_KernelJNI.Point_2_clone__SWIG_1(swigCPtr, this, Point_2.getCPtr(other), other);
  }

}
