/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Vector_3 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Vector_3(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vector_3 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Vector_3(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vector_3() {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_0(), true);
  }

  public Vector_3(Point_3 a, Point_3 b) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_1(Point_3.getCPtr(a), a, Point_3.getCPtr(b), b), true);
  }

  public Vector_3(Segment_3 s) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_2(Segment_3.getCPtr(s), s), true);
  }

  public Vector_3(Ray_3 r) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_3(Ray_3.getCPtr(r), r), true);
  }

  public Vector_3(Line_3 l) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_4(Line_3.getCPtr(l), l), true);
  }

  public Vector_3(int x, int y, int z) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_5(x, y, z), true);
  }

  public Vector_3(double x, double y, double z) {
    this(CGAL_KernelJNI.new_Vector_3__SWIG_6(x, y, z), true);
  }

  public double x() {
    return CGAL_KernelJNI.Vector_3_x(swigCPtr, this);
  }

  public double y() {
    return CGAL_KernelJNI.Vector_3_y(swigCPtr, this);
  }

  public double z() {
    return CGAL_KernelJNI.Vector_3_z(swigCPtr, this);
  }

  public double cartesian(int c) {
    return CGAL_KernelJNI.Vector_3_cartesian(swigCPtr, this, c);
  }

  public Direction_3 direction() {
    return new Direction_3(CGAL_KernelJNI.Vector_3_direction__SWIG_0(swigCPtr, this), true);
  }

  public void direction(Direction_3 ref) {
    CGAL_KernelJNI.Vector_3_direction__SWIG_1(swigCPtr, this, Direction_3.getCPtr(ref), ref);
  }

  public double squared_length() {
    return CGAL_KernelJNI.Vector_3_squared_length(swigCPtr, this);
  }

  public int dimension() {
    return CGAL_KernelJNI.Vector_3_dimension(swigCPtr, this);
  }

  public void set_coordinates(double x, double y, double z) {
    CGAL_KernelJNI.Vector_3_set_coordinates(swigCPtr, this, x, y, z);
  }

  public boolean equals(Vector_3 r) {
    return CGAL_KernelJNI.Vector_3_equals(swigCPtr, this, Vector_3.getCPtr(r), r);
  }

  public String toString() {
    return CGAL_KernelJNI.Vector_3_toString(swigCPtr, this);
  }

  public Vector_3 clone() {
    return new Vector_3(CGAL_KernelJNI.Vector_3_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Vector_3 other) {
    CGAL_KernelJNI.Vector_3_clone__SWIG_1(swigCPtr, this, Vector_3.getCPtr(other), other);
  }

}
