/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.4
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */

package CGAL.Kernel;

public class Vector_2 {
  private long swigCPtr;
  protected boolean swigCMemOwn;

  public Vector_2(long cPtr, boolean cMemoryOwn) {
    swigCMemOwn = cMemoryOwn;
    swigCPtr = cPtr;
  }

  public static long getCPtr(Vector_2 obj) {
    return (obj == null) ? 0 : obj.swigCPtr;
  }

  protected void finalize() {
    delete();
  }

  public synchronized void delete() {
    if (swigCPtr != 0) {
      if (swigCMemOwn) {
        swigCMemOwn = false;
        CGAL_KernelJNI.delete_Vector_2(swigCPtr);
      }
      swigCPtr = 0;
    }
  }

  public Vector_2() {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_0(), true);
  }

  public Vector_2(Point_2 a, Point_2 b) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_1(Point_2.getCPtr(a), a, Point_2.getCPtr(b), b), true);
  }

  public Vector_2(Segment_2 s) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_2(Segment_2.getCPtr(s), s), true);
  }

  public Vector_2(Ray_2 r) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_3(Ray_2.getCPtr(r), r), true);
  }

  public Vector_2(Line_2 l) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_4(Line_2.getCPtr(l), l), true);
  }

  public Vector_2(int x, int y) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_5(x, y), true);
  }

  public Vector_2(double x, double y) {
    this(CGAL_KernelJNI.new_Vector_2__SWIG_6(x, y), true);
  }

  public double x() {
    return CGAL_KernelJNI.Vector_2_x(swigCPtr, this);
  }

  public double y() {
    return CGAL_KernelJNI.Vector_2_y(swigCPtr, this);
  }

  public double cartesian(int c) {
    return CGAL_KernelJNI.Vector_2_cartesian(swigCPtr, this, c);
  }

  public int dimension() {
    return CGAL_KernelJNI.Vector_2_dimension(swigCPtr, this);
  }

  public Direction_2 direction() {
    return new Direction_2(CGAL_KernelJNI.Vector_2_direction__SWIG_0(swigCPtr, this), true);
  }

  public void direction(Direction_2 ref) {
    CGAL_KernelJNI.Vector_2_direction__SWIG_1(swigCPtr, this, Direction_2.getCPtr(ref), ref);
  }

  public Vector_2 perpendicular(Orientation c) {
    return new Vector_2(CGAL_KernelJNI.Vector_2_perpendicular__SWIG_0(swigCPtr, this, c.swigValue()), true);
  }

  public void perpendicular(Orientation c, Vector_2 ret) {
    CGAL_KernelJNI.Vector_2_perpendicular__SWIG_1(swigCPtr, this, c.swigValue(), Vector_2.getCPtr(ret), ret);
  }

  public double squared_length() {
    return CGAL_KernelJNI.Vector_2_squared_length(swigCPtr, this);
  }

  public boolean equals(Vector_2 r) {
    return CGAL_KernelJNI.Vector_2_equals(swigCPtr, this, Vector_2.getCPtr(r), r);
  }

  public String toString() {
    return CGAL_KernelJNI.Vector_2_toString(swigCPtr, this);
  }

  public Vector_2 clone() {
    return new Vector_2(CGAL_KernelJNI.Vector_2_clone__SWIG_0(swigCPtr, this), true);
  }

  public void clone(Vector_2 other) {
    CGAL_KernelJNI.Vector_2_clone__SWIG_1(swigCPtr, this, Vector_2.getCPtr(other), other);
  }

}
